SetupShop/Controllers/SetupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SetupShop.Areas.Identity.Data;
using SetupShop.Data;
using SetupShop.Models;

namespace SetupShop.Controllers
{
    [Authorize(Policy = "RequireAuthor")]
    public class SetupsController : Controller
    {
        private readonly SetupShopContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<SetupShopUser> _userManager;

        public SetupsController(SetupShopContext context, IWebHostEnvironment webHostEnvironment, UserManager<SetupShopUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Setups
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return _context.Setups != null ?
                        View(await _context.Setups.ToListAsync()) :
                        Problem("Entity set 'SetupContext.Setup'  is null.");
        }

        public async Task<IActionResult> Author()
        {
            return _context.Setups != null ?
                          View(await _context.Setups.ToListAsync()) :
                          Problem("Entity set 'SetupContext.Setup'  is null.");
        }

        // GET: Setups/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Setups == null)
            {
                return NotFound();
            }

            var setup = await _context.Setups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (setup == null)
            {
                return NotFound();
            }

            return View(setup);
        }

        // GET: Setups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Setups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Setup setup)
        {
            if (ModelState.IsValid)
            {
                if (setup.ImageUpload != null)
                {
                    string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media");
                    string imageName = Guid.NewGuid().ToString() + "_" + setup.ImageUpload.FileName;

                    imageName = imageName.Replace(" ", "_");

                    string filePath = Path.Combine(uploadsDir, imageName);

                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await setup.ImageUpload.CopyToAsync(fs);
                    fs.Close();

                    setup.Image = imageName;
                }

                if (setup.FileUpload != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        var file = setup.FileUpload;

                        await file.CopyToAsync(memoryStream);

                        setup.FileName = file.FileName;
                        setup.FileType = file.ContentType;
                        setup.File = memoryStream.ToArray();
                    }
                }

                _context.Add(setup);
                await _context.SaveChangesAsync();

                TempData["Success"] = "The setup has been added!";

                return RedirectToAction("Author");
            }

            return View(setup);
        }

        // GET: Setups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Setups == null)
            {
                return NotFound();
            }

            var setup = await _context.Setups.FindAsync(id);
            if (setup == null)
            {
                return NotFound();
            }
            return View(setup);
        }

        // POST: Setups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Setup setup)
        {
            if (id != setup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (setup.ImageUpload != null)
                {
                    string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media");
                    string imageName = Guid.NewGuid().ToString() + "_" + setup.ImageUpload.FileName;

                    imageName = imageName.Replace(" ", "_");

                    string filePath = Path.Combine(uploadsDir, imageName);

                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await setup.ImageUpload.CopyToAsync(fs);
                    fs.Close();

                    setup.Image = imageName;
                }

                if (setup.FileUpload != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        var file = setup.FileUpload;

                        await file.CopyToAsync(memoryStream);

                        setup.FileName = file.FileName;
                        setup.FileType = file.ContentType;
                        setup.File = memoryStream.ToArray();
                    }
                }

                _context.Update(setup);
                await _context.SaveChangesAsync();

                TempData["Success"] = "The product has been edited!";
            }

            return View(setup);
        }

        // GET: Setups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Setups == null)
            {
                return NotFound();
            }

            var setup = await _context.Setups
                .FirstOrDefaultAsync(m => m.Id == id);

            if (setup == null)
            {
                return NotFound();
            }

            if (!string.Equals(setup.Image, "noimage.png"))
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media");
                string oldImagePath = Path.Combine(uploadsDir, setup.Image);

                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            _context.Setups.Remove(setup);
            await _context.SaveChangesAsync();

            TempData["Success"] = "The product has been deleted!";

            return RedirectToAction("Author");
        }

        // POST: Setups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Setups == null)
            {
                return Problem("Entity set 'SetupContext.Setup'  is null.");
            }
            var setup = await _context.Setups.FindAsync(id);
            if (setup != null)
            {
                _context.Setups.Remove(setup);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Download(int id)
        {
            using (var db = _context)
            {
                var fileUpload = await db.Setups.FindAsync(id);

                if (fileUpload != null)
                {
                    return File(fileUpload.File, fileUpload.FileType, fileUpload.FileName);
                }
            }

            return NotFound("File doesn't exist.");
        }

        private bool SetupExists(int id)
        {
            return (_context.Setups?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SetupShop/Data/Components/SmallCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;
using SetupShop.Models;
using SetupShop.Models.ViewModels;

namespace SetupShop.Data.Components
{
    public class SmallCartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart");
            SmallCartViewModel smallCartVM;

            if (cart == null || cart.Count == 0) 
            {
                smallCartVM = null;
            }
            else
            {
                smallCartVM = new()
                {
                    NumberOfItems = cart.Sum(x => x.Quantity),
                    TotalAmount = cart.Sum(x => x.Quantity * x.Price)
                };
            }

            return View(smallCartVM);
        }
    }
}

SetupShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SLW Garage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SetupShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.typekit.net/biz8nsf.css">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
    <header>
        <nav class="navbar navbar-dark navbar-expand-sm navbar-toggleable-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/media/logo-full.svg" alt="SLW Garage Logo"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Setups" asp-action="Index">Browse Setups</a>
                        </li>
                    </ul>
                    <vc:small-cart />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main class="pb-3">
            <div class="row">
                <div class="col mt-4">
                    <partial name="_NotificationPartial" />
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container text-center">
            &copy; 2023 - SLW Garage by <a href="#">Samuel Ward</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SetupShop/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}