SetupShop/Models/Setup.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using SetupShop.Areas.Identity.Data;
using SetupShop.Data.Validation;
using System.ComponentModel.DataAnnotations.Schema;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace SetupShop.Models
{
    public class Setup
    {
        // Properties
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; }

        public string Author { get; set; }

        public byte[] File { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }

        [NotMapped]
        public IFormFile FileUpload { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        public string Car { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        public string Track { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        public string Season { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        public string Week { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        public string Series { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        public string VideoUrl { get; set; }

        [Required]
        [Column(TypeName = "decimal(8, 2)")]
        public decimal Price { get; set; }

        public string Image { get; set; } = "noimage.png";

        [NotMapped]
        [FileExtension]
        public IFormFile ImageUpload { get; set; }

        public ICollection<UserSetup> UserSetups { get; set; }
    }
}

SetupShop/Controllers/MySetupsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SetupShop.Areas.Identity.Data;
using SetupShop.Data;
using SetupShop.Models;
using SQLitePCL;
using System.Security.Claims;

namespace SetupShop.Controllers
{
    public class MySetupsController : Controller
    {
        private readonly SetupShopContext _context;
        private readonly UserManager<SetupShopUser> _userManager;

        public MySetupsController(SetupShopContext context, IWebHostEnvironment webHostEnvironment, UserManager<SetupShopUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var setups = _context.Users
                .Where(u => u.Id == userId)
                .Include(u => u.UserSetups)
                    .ThenInclude(us => us.Setup)
                .SelectMany(u => u.UserSetups)
                .Select(us => us.Setup)
                .ToList();

            return View(setups);
        }
    }
}

SetupShop/Controllers/SetupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SetupShop.Areas.Identity.Data;
using SetupShop.Data;
using SetupShop.Models;

namespace SetupShop.Controllers
{
    [Authorize(Policy = "RequireAuthor")]
    public class SetupsController : Controller
    {
        private readonly SetupShopContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<SetupShopUser> _userManager;

        public SetupsController(SetupShopContext context, IWebHostEnvironment webHostEnvironment, UserManager<SetupShopUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Setups
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return _context.Setups != null ?
                        View(await _context.Setups.ToListAsync()) :
                        Problem("Entity set 'SetupContext.Setup'  is null.");
        }

        public async Task<IActionResult> Author()
        {
            return _context.Setups != null ?
                          View(await _context.Setups.ToListAsync()) :
                          Problem("Entity set 'SetupContext.Setup'  is null.");
        }

        // GET: Setups/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Setups == null)
            {
                return NotFound();
            }

            var setup = await _context.Setups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (setup == null)
            {
                return NotFound();
            }

            return View(setup);
        }

        // GET: Setups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Setups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Setup setup)
        {
            if (ModelState.IsValid)
            {
                if (setup.ImageUpload != null)
                {
                    string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media");
                    string imageName = Guid.NewGuid().ToString() + "_" + setup.ImageUpload.FileName;

                    imageName = imageName.Replace(" ", "_");

                    string filePath = Path.Combine(uploadsDir, imageName);

                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await setup.ImageUpload.CopyToAsync(fs);
                    fs.Close();

                    setup.Image = imageName;
                }

                if (setup.FileUpload != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        var file = setup.FileUpload;

                        await file.CopyToAsync(memoryStream);

                        setup.FileName = file.FileName;
                        setup.FileType = file.ContentType;
                        setup.File = memoryStream.ToArray();
                    }
                }

                _context.Add(setup);
                await _context.SaveChangesAsync();

                TempData["Success"] = "The setup has been added!";

                return RedirectToAction("Author");
            }

            return View(setup);
        }

        // GET: Setups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Setups == null)
            {
                return NotFound();
            }

            var setup = await _context.Setups.FindAsync(id);
            if (setup == null)
            {
                return NotFound();
            }
            return View(setup);
        }

        // POST: Setups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Setup setup)
        {
            if (id != setup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (setup.ImageUpload != null)
                {
                    string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media");
                    string imageName = Guid.NewGuid().ToString() + "_" + setup.ImageUpload.FileName;

                    imageName = imageName.Replace(" ", "_");

                    string filePath = Path.Combine(uploadsDir, imageName);

                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await setup.ImageUpload.CopyToAsync(fs);
                    fs.Close();

                    setup.Image = imageName;
                }

                if (setup.FileUpload != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        var file = setup.FileUpload;

                        await file.CopyToAsync(memoryStream);

                        setup.FileName = file.FileName;
                        setup.FileType = file.ContentType;
                        setup.File = memoryStream.ToArray();
                    }
                }

                _context.Update(setup);
                await _context.SaveChangesAsync();

                TempData["Success"] = "The product has been edited!";
            }

            return View(setup);
        }

        // GET: Setups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Setups == null)
            {
                return NotFound();
            }

            var setup = await _context.Setups
                .FirstOrDefaultAsync(m => m.Id == id);

            if (setup == null)
            {
                return NotFound();
            }

            if (!string.Equals(setup.Image, "noimage.png"))
            {
                string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "media");
                string oldImagePath = Path.Combine(uploadsDir, setup.Image);

                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }

            _context.Setups.Remove(setup);
            await _context.SaveChangesAsync();

            TempData["Success"] = "The product has been deleted!";

            return RedirectToAction("Author");
        }

        // POST: Setups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Setups == null)
            {
                return Problem("Entity set 'SetupContext.Setup'  is null.");
            }
            var setup = await _context.Setups.FindAsync(id);
            if (setup != null)
            {
                _context.Setups.Remove(setup);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Download(int id)
        {
            using (var db = _context)
            {
                var fileUpload = await db.Setups.FindAsync(id);

                if (fileUpload != null)
                {
                    return File(fileUpload.File, fileUpload.FileType, fileUpload.FileName);
                }
            }

            return NotFound("File doesn't exist.");
        }

        private bool SetupExists(int id)
        {
            return (_context.Setups?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SetupShop/Views/Setups/Author.cshtml
@using Microsoft.AspNetCore.Identity
@using SetupShop.Areas.Identity.Data

@inject SignInManager<SetupShopUser> SignInManager
@inject UserManager<SetupShopUser> UserManager

@model IEnumerable<SetupShop.Models.Setup>

@{
    ViewData["Title"] = "Setups";
}

<h2>Manage Setups</h2>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.File)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Car)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Track)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Season)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Week)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Series)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VideoUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="/media/@Html.DisplayFor(modelItem => item.Image)" class="img-fluid" alt="" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Car)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Track)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Season)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Week)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Series)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VideoUrl)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SetupShop/Views/Setups/Create.cshtml
@using Microsoft.AspNetCore.Identity;
@using SetupShop.Areas.Identity.Data;

@model SetupShop.Models.Setup

@inject UserManager<SetupShopUser> UserManager

@{
    ViewData["Title"] = "Create Setup";
}

<h2>Create Setup</h2>

<hr />
<div class="row">
    <div class="col-md-7 mb-5">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" value="@((await UserManager.GetUserAsync(User)).DisplayName)" readonly />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileUpload" class="control-label">File</label>
                <input asp-for="FileUpload" type="file" class="form-control" />
                <span asp-validation-for="FileUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Car" class="control-label"></label>
                <input asp-for="Car" class="form-control" />
                <span asp-validation-for="Car" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Track" class="control-label"></label>
                <input asp-for="Track" class="form-control" />
                <span asp-validation-for="Track" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Season" class="control-label"></label>
                <input asp-for="Season" class="form-control" />
                <span asp-validation-for="Season" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Week" class="control-label"></label>
                <input asp-for="Week" class="form-control" />
                <span asp-validation-for="Week" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Series" class="control-label"></label>
                <input asp-for="Series" class="form-control" />
                <span asp-validation-for="Series" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoUrl" class="control-label"></label>
                <input asp-for="VideoUrl" class="form-control" />
                <span asp-validation-for="VideoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label">Image</label>
                <input asp-for="ImageUpload" class="form-control" />
                <label>Uploaded Image</label>
                <img id="imgpreview" src="/media/noimage.png" class="pt-2" alt="Image Preview"/>
                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn green" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn text-white" asp-action="Author">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script>
        $("#ImageUpload").change(function() {
            readURL(this);
        });
    </script>
}

SetupShop/Views/Setups/Delete.cshtml
@model SetupShop.Models.Setup

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Setup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.File)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.File)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Track)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Track)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Season)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Season)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Week)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Week)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Series)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Series)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VideoUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VideoUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SetupShop/Views/Setups/Details.cshtml
@model SetupShop.Models.Setup

@{
    ViewData["Title"] = @Html.DisplayFor(model => model.Name);
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<div class="col-12 setup">
    <img src="~/media/@Html.DisplayFor(model => model.Image)" class="img-fluid" alt="" />
    <div class="setup-wrapper">
        <div class="setup-info mb-3">
            <div class="setup-info-top">
                <div class="flex">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 15 15">
                        <path d="M13.5,13.5A3.75,3.75,0,1,0,9.75,9.75,3.749,3.749,0,0,0,13.5,13.5Zm0,1.875c-2.5,0-7.5,1.256-7.5,3.75V21H21V19.125C21,16.631,16,15.375,13.5,15.375Z" transform="translate(-6 -6)" fill="#fff" />
                    </svg>
                    <p>@Html.DisplayFor(model => model.Author)</p>
                </div>
                <div class="flex">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="11.25" viewBox="0 0 15 11.25">
                        <path d="M14.648,7.781H12.894l-.488-1.219A3.265,3.265,0,0,0,9.361,4.5H5.64A3.266,3.266,0,0,0,2.593,6.563L2.106,7.781H.352a.351.351,0,0,0-.341.437l.176.7a.351.351,0,0,0,.341.266h.588a1.862,1.862,0,0,0-.647,1.406V12a1.86,1.86,0,0,0,.469,1.228v1.584a.938.938,0,0,0,.938.938h.938a.938.938,0,0,0,.938-.938v-.938h7.5v.938a.938.938,0,0,0,.938.938h.938a.938.938,0,0,0,.938-.938V13.228A1.859,1.859,0,0,0,14.531,12V10.594a1.863,1.863,0,0,0-.647-1.406h.588a.351.351,0,0,0,.341-.266l.176-.7a.352.352,0,0,0-.341-.437ZM4.334,7.259A1.406,1.406,0,0,1,5.64,6.375H9.361a1.406,1.406,0,0,1,1.306.884l.584,1.46H3.75l.584-1.46ZM2.813,11.994a.935.935,0,1,1,0-1.869,1.8,1.8,0,0,1,1.406,1.4C4.219,12.088,3.375,11.994,2.813,11.994Zm9.375,0c-.563,0-1.406.093-1.406-.467a1.8,1.8,0,0,1,1.406-1.4.935.935,0,1,1,0,1.869Z" transform="translate(0 -4.5)" fill="#fff" />
                    </svg>
                    <p>@Html.DisplayFor(model => model.Car)</p>
                </div>
                <div class="flex">
                    <svg xmlns="http://www.w3.org/2000/svg" width="10.5" height="15" viewBox="0 0 10.5 15">
                        <path d="M12.75,3A5.246,5.246,0,0,0,7.5,8.25c0,3.937,5.25,9.75,5.25,9.75S18,12.187,18,8.25A5.246,5.246,0,0,0,12.75,3Zm0,7.125A1.875,1.875,0,1,1,14.625,8.25,1.876,1.876,0,0,1,12.75,10.125Z" transform="translate(-7.5 -3)" fill="#fff" />
                    </svg>
                    <p>@Html.DisplayFor(model => model.Track)</p>
                </div>
                <div class="flex">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15.243" viewBox="0 0 15 15.243">
                        <path id="Icon_awesome-flag-checkered" data-name="Icon awesome-flag-checkered" d="M7.564,5.651V7.678c.777.176,1.468.464,2.191.664V6.312c-.774-.173-1.471-.461-2.191-.661ZM14.211,1.99a8.692,8.692,0,0,1-3.483.95C9.136,2.939,7.817,1.9,5.811,1.9a5.788,5.788,0,0,0-2.024.357,1.667,1.667,0,1,0-2.509.771V14.525a.713.713,0,0,0,.714.714h.476a.713.713,0,0,0,.714-.714v-2.81a8.3,8.3,0,0,1,3.405-.658c1.6,0,2.911,1.036,4.918,1.036a6.22,6.22,0,0,0,3.647-1.218.95.95,0,0,0,.411-.786V2.853A.951.951,0,0,0,14.211,1.99Zm-8.838,7.7a9.378,9.378,0,0,0-2.191.494v-2.1a8.516,8.516,0,0,1,2.191-.518Zm8.764-4a9.5,9.5,0,0,1-2.191.711V8.512a5.533,5.533,0,0,0,2.191-.774v2.1a4.81,4.81,0,0,1-2.191.807V8.512a5.035,5.035,0,0,1-2.191-.167v2.006a17.368,17.368,0,0,0-2.191-.634V7.678a6.617,6.617,0,0,0-2.191-.113V5.481A10.5,10.5,0,0,0,3.182,6.1V4A8.525,8.525,0,0,1,5.373,3.35V5.481a5.063,5.063,0,0,1,2.191.17V3.645a16.947,16.947,0,0,0,2.191.634V6.315a5.671,5.671,0,0,0,2.191.08V4.255a10.532,10.532,0,0,0,2.191-.67Z" transform="translate(-0.563 0.003)" fill="#fff" />
                    </svg>
                    <p>@Html.DisplayFor(model => model.Series) - @Html.DisplayFor(model => model.Season)</p>
                </div>
            </div>
        </div>
        <p>All our setups include qualifying and race setups, replay files and lap-files for comparison as well as telemetry files for use in telemetry software like MOTEC.</p>
        <div class="mb-5">
            @Html.ActionLink("Download", "Download", "Setups", new { id = Model.Id }, new { @class = "btn green text-white" })
        </div>
        <div>
            <h3>Lap Video</h3>
            <iframe 
                src="@Html.DisplayFor(model => model.VideoUrl)"
                title="YouTube video player" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                allowfullscreen>
            </iframe>
        </div>
    </div>
</div>

<div>
    <a class="btn text-white mt-4" asp-controller="MySetups" asp-action="Index">Back to List</a>
</div>

SetupShop/Views/Setups/Edit.cshtml
@model SetupShop.Models.Setup

@{
    ViewData["Title"] = "Edit Setup";
}

<h2>Edit Setup</h2>

<hr />
<div class="row">
    <div class="col-md-7 mb-5">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Image" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Current File</label>
                <p>@Model.FileName</p>
            </div>
            <div class="form-group">
                <label asp-for="FileUpload" class="control-label">File</label>
                <input asp-for="FileUpload" type="file" class="form-control" />
                <span asp-validation-for="FileUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Car" class="control-label"></label>
                <input asp-for="Car" class="form-control" />
                <span asp-validation-for="Car" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Track" class="control-label"></label>
                <input asp-for="Track" class="form-control" />
                <span asp-validation-for="Track" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Season" class="control-label"></label>
                <input asp-for="Season" class="form-control" />
                <span asp-validation-for="Season" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Week" class="control-label"></label>
                <input asp-for="Week" class="form-control" />
                <span asp-validation-for="Week" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Series" class="control-label"></label>
                <input asp-for="Series" class="form-control" />
                <span asp-validation-for="Series" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoUrl" class="control-label"></label>
                <input asp-for="VideoUrl" class="form-control" />
                <span asp-validation-for="VideoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Current Image</label>
                <img src="/media/@Model.Image" width="200" alt="Current Image"/>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label">Image</label>
                <input asp-for="ImageUpload" class="form-control" />
                <label>Uploaded Image</label>
                <img id="imgpreview" src="/media/noimage.png" class="pt-2" alt="Image Preview" />
                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button class="btn green text-white">Edit</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn text-white" asp-action="Author">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $("#ImageUpload").change(function () {
            readURL(this);
        });
    </script>
}